version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./log/php:/var/log
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network



  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www
      - ./log/nginx:/var/log
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network


  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: xJHtxj8G
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql/
      - ./log/mysql:/var/log
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network


#Docker Networks
networks:
  laravel-network:
    driver: bridge

#Volumes
volumes:
  mysql-data:
    driver: local